language: objective-c
osx_image: xcode10.2
before_script:
  - carthage update --platform ios
script:
  - bundle exec fastlane scan --code_coverage true --device 'iPhone 8' --project MapleBacon.xcodeproj --scheme MapleBacon
  - bundle exec danger
  - swiftlint
after_success:
  - bash <(curl -s https://codecov.io/bash)