name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Deploy to CocoaPods
      run: |
        gem install cocoapods
    - uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.9
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}